function ResultsTable = createAntennaResultsTable(totalMeasurements)
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    % Add measurements column.
    varNames = {'Theta (deg)',... 
                'Phi (deg)',...
                'Frequency (MHz)',...
            	'Gain (dBi)',...
            	'Return Loss (dB)'...
            	'Return Loss (deg)'
    };
    
    varTypes = repmat({'double'}, 1, length(varNames));
    
    % Create the Antenna results table.
    ResultsTable = table('Size', [totalMeasurements, length(varNames)], ...
                         'VariableTypes', varTypes, ...
                         'VariableNames', varNames);
end
